version: "3.9"

services:
  supabase-db:
    image: postgres:16
    container_name: checkbox_supabase_db
    restart: always
    environment:
      POSTGRES_PASSWORD: supabase
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      # Persistent named volume
      - db_data:/var/lib/postgresql/data
      # Init scripts (extensions, etc.)
      - ./docker/init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 15s

  redis:
    image: redis:7
    container_name: checkbox_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: checkbox_backend
    restart: always
    environment:
      REDIS_URL: redis://redis:6379
      NODE_ENV: local
      SUPABASE_DB_URL: postgres://postgres:supabase@supabase-db:5432/postgres
      DB_HOST: supabase-db
      DB_USER: postgres
      DB_PASSWORD: supabase
      DB_NAME: postgres
    ports:
      - "4000:4000"
    depends_on:
      - supabase-db
      - redis
    networks:
      app-network:
        aliases:
          - backend

  webhook-service:
    build:
      context: "./Webhook"
      dockerfile: Dockerfile
    container_name: checkbox_webhook
    restart: always
    environment:
      BACKEND_API_URL: "http://backend:4000"
      REDIS_URL: redis://redis:6379
      NODE_ENV: local
      X_API_KEY: webhook-api-token
    ports:
      - "4001:4001"
    depends_on:
      - backend
      - redis
    networks:
      app-network:
        aliases:
          - webhook-service

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
